### ISSUE TITLE
I am getting "RangeError: msecs must be a non-negative finite number" error when I open http://localhost:8080

### ISSUE THREAD

**Issue by ishandutta2007** [kljensen/node-sse-example#2]
This the full stack trace:
RangeError: msecs must be a non-negative finite number
    at Object.exports.enroll (timers.js:160:11)
    at Socket.setTimeout (net.js:337:12)
    at /Users/dutishan/Documents/node/node-sse-example/app.js:22:13
    at callbacks (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/router/index.js:33:10)
    at next (/Users/dutishan/Documents/node/node-sse-example/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.expressInit [as handle](/Users/dutishan/Documents/node/node-sse-example/node_modules/express/lib/middleware.js:31:5)

**Comment by nowherenearithaca** [comment]
Use Number.MAX_VALUE instead of Infinity in the settimeout call. Worked for me.

**Comment by jbheren** [comment]
Thanks, it worked for me also.

**Comment by kljensen** [comment]
Closed by 6c52b8c1efd2dda06e2ac9b2e1949329582acf62
